-- 遷移資料 SQL
-- 請從本地前端的「資料遷移」頁面複製完整的 SQL 並替換此文件內容
-- 或直接在此文件中貼上從「資料遷移」頁面複製的 SQL

-- 範例格式（請替換為實際的 SQL）：
-- INSERT INTO users (id, email, display_name, role, avatar, status, created_at) VALUES ...
-- INSERT INTO leads (id, platform, platform_id, need, ...) VALUES ...
-- INSERT INTO audit_logs (id, lead_id, actor_uid, ...) VALUES ...
